# Generated by Django 6.0.4 on 2026-04-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(blank=True, default='', max_length=20)),
                ('service_type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('break', 'Break'), ('lunch', 'Lunch'), ('unavailable', 'Unavailable')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('has_inspo', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('client_history', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mani_inspo', models.ImageField(blank=True, null=True, upload_to='inspo/')),
                ('pedi_inspo', models.ImageField(blank=True, null=True, upload_to='inspo/')),
                ('spa_inspo', models.ImageField(blank=True, null=True, upload_to='inspo/')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Nail Technician', 'Nail Technician'), ('Spa Therapist', 'Spa Therapist')], default='Nail Technician', max_length=50)),
                ('is_technician', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
